name: harshit_portfolio
description: A modern Gen Z styled Flutter Web portfolio for Harshit Gyanchandani
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.2.0
  animations: ^2.0.10
  google_fonts: ^6.1.0
  rive_common: ^0.4.15
  rive: ^0.13.20
  shared_preferences_web: ^2.4.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
